### PR TITLE
Add user token authentication

### PR DESCRIPTION
**Pull request by tenuki**
I've just added user_token "authentication".

Can't figure out how to add a test for it, but you can use this for testing:

    __author__ = 'aweil'
    import os
    import unittest
    import discogs_client

    class UserTokenTest(unittest.TestCase):
        def setUp(self):
            with open(os.path.expanduser('~/.discogs_user_token'), 'rb') as f:
                self.discosgs_token = f.read().strip()
    
        def test_search(self):
            d = discogs_client.Client('TenukiWebApp1/0.1', user_token=self.discosgs_token)
            query_releases = d.search('Bit Shifter', type='artist')[0].releases[1].versions[0].labels[0].releases
            self.assertTrue( len(query_releases)>0)
    
    if __name__ == '__main__':
        unittest.main()

Please let me know when/where to add documentation when available and if you want I to documentate it in the readme.

### CODE REVIEW

**Comment by tenuki** [comment]
Also, I'm using in the test my registered user agent, please let me know if there is a default for this matter or if we should use an approach like the one for the user_token..

**Comment by rodneykeeling** [comment]
Code looks good to me. Neat feature to have! Please update the README file in the `Authorization` section that reflects this update.

**Comment by tenuki** [comment]
README updated, please take a look, english is not my native languaje..

**Comment by tenuki** [comment]
Changes done. Thanks!

**Comment by rodneykeeling** [comment]
Thanks! Looks good to me. :+1: 

Do you have a Discogs username? This is a feature I'd like to announce in the Discogs API forum, so if you'd like a shout-out/credit, please let me know!

**Comment by tenuki** [comment]
Thanks you you. My discogs username: tenuki. Thanks.

**Pull request merged**
