### PR TITLE
Make discogs_client python 2 & python 3 compatible

### PR DESCRIPTION
**Pull request by brunal**
This PR makes `discogs_client` python 2 *and* python 3 compatible.

Notables changes include:
- switch from python-oauth2 (no py3k compatibility) to [oauthlib](https://github.com/idan/oauthlib) (→ helps with #40)
- fix numerous pep8 error
- make tests deterministic

### CODE REVIEW

**Comment by rodneykeeling** [comment]
Nice! Thanks for the update, @brunal! :+1: from me.

**Comment by rodneykeeling** [comment]
@brunal looks like there's an issue with Python 3:
```
>>> import discogs_client
>>> d = discogs_client.Client('JesseTest/0.1')
>>> d.release(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foobar/Projects/discogs_client/discogs_client/models.py", line 490, in __repr__
    return '<Release %r %r>' % (self.id, self.title)
  File "/home/foobar/Projects/discogs_client/discogs_client/models.py", line 30, in __get__
    value = instance.fetch(self.name)
  File "/home/foobar/Projects/discogs_client/discogs_client/models.py", line 241, in fetch
    self.refresh()
  File "/home/foobar/Projects/discogs_client/discogs_client/models.py", line 207, in refresh
    data = self.client._get(self.data['resource_url'])
  File "/home/foobar/Projects/discogs_client/discogs_client/client.py", line 117, in _get
    return self._request('GET', url)
  File "/home/foobar/Projects/discogs_client/discogs_client/client.py", line 109, in _request
    body = json.loads(content)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Could you update `.travis.yml` to test for Python 3 as well?

**Comment by brunal** [comment]
That issue is now fixed! I hoped there's not more of them lying hidden.  I added python 3.{2,3,4} on travis.

I took the decision of making `Client.fetch()` return bytes, later decoded over `Client.fetch()` returning a string since the most important `Client` scions use `requests.request`, which returns bytes.

**Comment by rodneykeeling** [comment]
Hey @brunal,

I just tried walking through the OAuth process on the README (using Python 2), but I get an error on the `d.get_access_token('my_token')` step. Can you look into that?

Thanks,
Rodney

**Comment by brunal** [comment]
Done!

**Comment by brunal** [comment]
Hi,
I've been using my version with success for the past month. It solves other bugs, such as a 401 error on empty searches.

Do you plan on merging it? Otherwise we might have to use my fork for [beets](https://github.com/sampsyo/beets)

**Comment by rodneykeeling** [comment]
Thanks @brunal I'll look over this one today!

**Comment by rodneykeeling** [comment]
Following the steps on the README, I get this error when trying to execute `me.wantlist.add(ds.release(5))`:

`ValueError: Body contains parameters but Content-Type header was not set.`

The release was successfully added to my wantlist, but this error does not show on master.

**Comment by brunal** [comment]
The error message was actually incorrect: the Content-type was `application/json` instead of `application/x-www-url-formencoded`. I fixed it (as well as realease_id that should be a string and not an int for the request to be signed).

**Comment by rodneykeeling** [comment]
Great, looks good so far! Although now you must pass `get_access_token()` a unicode string (e.g., `get_access_token(u'abc123')`) or you get a warning message. Is that necessary?

**Comment by brunal** [comment]
That was not necessary, but preferable in case the verifier contains non-ascii characters - which is not the case. I removed it!

**Comment by rodneykeeling** [comment]
@brunal Perfect! Unless any of the other Discogs devs find issues within the week, I'll merge this on Friday. I hope that's alright. Thanks again for the great work on this! :beers:

**Comment by brunal** [comment]
Cool :-) It's been my pleasure.
Don't you think it would be time to tag a new version (the current one being `v2.0.2`)? That'd allow us folks at [beets](https://github.com/sampsyo/beets) to force it.

**Pull request merged**
